version: "3"

services:
  mysql:
    image: spendee-database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: expense_tracker
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net

  spendee-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/expense_tracker
    depends_on:
      - mysql

  spendee-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
networks:
  springapimysql-net:
